
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

      
  datasource:
    url: jdbc:h2:mem:backofficeDb
    driver-class-name: org.h2.Driver
    username: root
    password: '1111'
  mvc:
    hiddenmethod:
      filter:
        enabled: true

 
    
  mustache:
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      format_sql: true
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect


      
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
    info: DEBUG
      
      
      